
#theme: rtd-dropdown
#theme: mkdocs
#theme: simplex
#          readthedocs, solar, spacelab, pulse, darkly, united, sandstone, cerulean, simplex, litera, materia, journal,
#            cyborg, lux, cosmo, rtd-dropdown, minty, flatly, slate, mkdocs, yeti, superhero, lumen
theme: readthedocs

#mkdocs build

site_name: VIALAND 开发文档
#site_url: https://example.com/

nav:
    - <p><p><b>USER GUIDE</b></p>: userguid.md

    - User Interface: User.md
    - Smart Contracts : contracts.md  
    - Whitpaper: Whitpaper.md
    - Terms : terms.md  

    - <p><p><strong>DEVELOPER</strong></p>: developer.md
    
    - About : _note.md
    - Contracts : contracts.md
    - Versions : versions.md
    - Design : design.md  
    - Scripts : scripts.md
    - Events : events.md  
    - Gas : gas.md  
    - TEST : test.md  
    - Dev-Note : dev-note.md
    - Integration : integration.md
    - API : API.md
    - ADMIN MENU : Admin.md
    
