
#theme: rtd-dropdown
#theme: mkdocs
#theme: simplex
#          readthedocs, solar, spacelab, pulse, darkly, united, sandstone, cerulean, simplex, litera, materia, journal,
#            cyborg, lux, cosmo, rtd-dropdown, minty, flatly, slate, mkdocs, yeti, superhero, lumen
theme: readthedocs

#mkdocs build

site_name: VIALAND 开发文档
#site_url: https://example.com/

nav:
    - <p><strong>Backend</strong></p>: Backend.md
   
    - <p><b>Frontend</b></p>: Frontend.md

    - <p><b>Dev-Note</b></p>: dev-note.md

    - <p><b>Use mkDocs</b></p>: _note.md
  